/**
 * PsycheAI Master Psychological Model Authoritative Registry
 *
 * Source of truth:
 * - 11 Master Domains
 * - 37 Active Master Constructs
 * - 91 Granular Master Facets
 * - 469 Administered Items (455 Psychological + 14 Response Quality)
 * - 16 Assessment Modules
 */

export interface MasterFacetDefinition {
  facetId: string;
  code: string;
  nameTr: string;
  nameEn: string;
  domainId: string;
  constructId: string;
  expectedItemCount: number;
  scientificDefinitionTr: string;
  inclusionCriteria?: string[];
  referenceInstruments?: string[];
}

export interface MasterConstructDefinition {
  constructId: string;
  code: string;
  nameTr: string;
  nameEn: string;
  domainId: string;
  facetIds: string[];
  allowsDirectAggregation: boolean;
  scientificRationaleTr: string;
}

export interface MasterDomainDefinition {
  domainId: string;
  code: string;
  nameTr: string;
  nameEn: string;
  descriptionTr: string;
  color?: string;
  sortOrder: number;
  constructIds: string[];
  facetIds: string[];
}

// -----------------------------------------------------------------------------
// 1. 11 AUTHORITATIVE MASTER DOMAINS
// -----------------------------------------------------------------------------
export const MASTER_DOMAINS: MasterDomainDefinition[] = [
  {
    domainId: 'core_personality',
    code: 'core_personality',
    nameTr: 'Temel Kişilik Boyutları (HEXACO)',
    nameEn: 'Core Personality (HEXACO)',
    descriptionTr: 'HEXACO 6 faktör modeli temelinde bireyin 6 geniş kişilik faktörü ve 24 alt boyutu.',
    color: '#3B82F6',
    sortOrder: 1,
    constructIds: [
      'hexaco_honesty_humility',
      'hexaco_emotionality',
      'hexaco_extraversion',
      'hexaco_agreeableness',
      'hexaco_conscientiousness',
      'hexaco_openness',
    ],
    facetIds: [
      'sincerity',
      'fairness',
      'greed_avoidance',
      'modesty',
      'fearfulness',
      'anxiety',
      'dependence',
      'sentimentality',
      'social_self_esteem',
      'social_boldness',
      'sociability',
      'liveliness',
      'forgivingness',
      'gentleness',
      'flexibility',
      'patience',
      'organization',
      'diligence',
      'perfectionism',
      'prudence',
      'aesthetic_appreciation',
      'inquisitiveness',
      'creativity',
      'unconventionality',
    ],
  },
  {
    domainId: 'self_system',
    code: 'self_system',
    nameTr: 'Benlik Sistemi ve Kimlik Yapısı',
    nameEn: 'Self-System & Identity Structure',
    descriptionTr: 'Benlik saygısı, öz-şefkat, öz-yeterlik, denetim odağı, belirginlik ve otantiklik dinamikleri.',
    color: '#10B981',
    sortOrder: 2,
    constructIds: [
      'core_self_esteem',
      'self_compassion',
      'generalized_self_efficacy',
      'locus_of_control',
      'self_concept_clarity',
      'authenticity',
    ],
    facetIds: [
      'core_self_esteem',
      'contingent_self_worth',
      'self_compassion',
      'generalized_self_efficacy',
      'locus_of_control_internal',
      'locus_of_control_external',
      'self_concept_clarity',
      'authenticity',
    ],
  },
  {
    domainId: 'emotion_regulation',
    code: 'emotion_regulation',
    nameTr: 'Duygu Dinamikleri ve Duygu Düzenleme',
    nameEn: 'Affective Dynamics & Emotion Regulation',
    descriptionTr: 'Bilişsel yeniden değerlendirme, baskılama, mizaç duygulanımı, sıkıntı toleransı ve öz-bilinçli duygular.',
    color: '#EC4899',
    sortOrder: 3,
    constructIds: [
      'cognitive_reappraisal',
      'expressive_suppression',
      'affective_tone',
      'distress_tolerance',
      'self_conscious_emotions',
    ],
    facetIds: [
      'cognitive_reappraisal',
      'expressive_suppression',
      'positive_affect_trait',
      'negative_affect_trait',
      'affect_intensity',
      'distress_tolerance',
      'experiential_avoidance',
      'shame_proneness',
      'guilt_proneness',
    ],
  },
  {
    domainId: 'cognition_decision',
    code: 'cognition_decision',
    nameTr: 'Biliş, Üstbiliş ve Karar Tarzları',
    nameEn: 'Cognition, Metacognition & Decision Styles',
    descriptionTr: 'Biliş ihtiyacı, belirsizlik kapatma, rasyonel/sezgisel düşünme, bilişsel esneklik ve karar yönelimi.',
    color: '#8B5CF6',
    sortOrder: 4,
    constructIds: [
      'epistemic_drive',
      'thinking_styles',
      'cognitive_adaptability',
      'decision_orientation',
    ],
    facetIds: [
      'need_for_cognition',
      'need_for_cognitive_closure',
      'rational_analytical_thinking',
      'intuitive_experiential_thinking',
      'cognitive_flexibility',
      'intolerance_of_uncertainty',
      'rumination_brooding',
      'decision_style_maximizing',
      'procrastination_tendency',
    ],
  },
  {
    domainId: 'self_regulation',
    code: 'self_regulation',
    nameTr: 'Öz-Düzenleme, İrade ve Dürtü Kontrolü',
    nameEn: 'Self-Regulation, Volition & Impulse Control',
    descriptionTr: 'Çok boyutlu dürtüsellik (UPPS-P), genel öz-kontrol, erteleme tercihi ve uzun vadeli azim.',
    color: '#F59E0B',
    sortOrder: 5,
    constructIds: [
      'impulsivity_uppsp',
      'volitional_stamina',
    ],
    facetIds: [
      'uppsp_negative_urgency',
      'uppsp_positive_urgency',
      'uppsp_lack_of_premeditation',
      'uppsp_lack_of_perseverance',
      'uppsp_sensation_seeking',
      'general_self_control',
      'delay_discounting_preference',
      'long_term_grit',
    ],
  },
  {
    domainId: 'motivation_values',
    code: 'motivation_values',
    nameTr: 'Motivasyon, İhtiyaçlar ve Evrensel Değerler',
    nameEn: 'Motivation, Needs & Human Values',
    descriptionTr: 'Temel psikolojik ihtiyaçlar (Öz-Belirleme), Schwartz evrensel insan değerleri ve varoluşsal anlam.',
    color: '#14B8A6',
    sortOrder: 6,
    constructIds: [
      'basic_psychological_needs',
      'universal_values',
      'existential_meaning',
    ],
    facetIds: [
      'autonomy_need_satisfaction',
      'competence_need_satisfaction',
      'relatedness_need_satisfaction',
      'schwartz_openness_to_change',
      'schwartz_self_transcendence',
      'schwartz_conservation',
      'schwartz_self_enhancement',
      'presence_of_meaning',
      'search_for_meaning',
    ],
  },
  {
    domainId: 'social_relational',
    code: 'social_relational',
    nameTr: 'Kişilerarası ve İlişkisel Dinamikler',
    nameEn: 'Interpersonal & Relational Dynamics',
    descriptionTr: 'Yetişkin bağlanma boyutları, çok boyutlu empati, ilişkisel sınırlar ve çatışma çözme stilleri.',
    color: '#6366F1',
    sortOrder: 7,
    constructIds: [
      'attachment_system',
      'multidimensional_empathy',
      'social_agency_boundaries',
      'conflict_styles',
    ],
    facetIds: [
      'attachment_anxiety',
      'attachment_avoidance',
      'cognitive_perspective_taking',
      'empathic_concern',
      'assertiveness',
      'social_connectedness',
      'rejection_sensitivity_nonclinical',
      'cooperation_orientation',
      'conflict_avoidance',
    ],
  },
  {
    domainId: 'wellbeing_vitality',
    code: 'wellbeing_vitality',
    nameTr: 'Öznel İyi Oluş ve Yaşam Canlılığı',
    nameEn: 'Subjective Well-Being & Vitality',
    descriptionTr: 'Psikolojik gelişme, öznel canlılık ve yaşam memnuniyeti göstergeleri.',
    color: '#06B6D4',
    sortOrder: 8,
    constructIds: [
      'psychological_flourishing',
      'life_satisfaction',
    ],
    facetIds: [
      'flourishing_scale',
      'subjective_vitality',
      'satisfaction_with_life',
    ],
  },
  {
    domainId: 'coping_resilience',
    code: 'coping_resilience',
    nameTr: 'Başa Çıkma Stratejileri ve Stres Dayanıklılığı',
    nameEn: 'Coping Strategies & Stress Resilience',
    descriptionTr: 'Ego sağlamlığı, stres toparlanması, problem odaklı ve duygu odaklı başa çıkma yönelimleri.',
    color: '#0284C7',
    sortOrder: 9,
    constructIds: [
      'psychological_resilience',
      'coping_orientations',
    ],
    facetIds: [
      'ego_resilience',
      'stress_recovery',
      'problem_focused_coping',
      'emotion_focused_coping',
    ],
  },
  {
    domainId: 'creativity_curiosity',
    code: 'creativity_curiosity',
    nameTr: 'Yaratıcılık, Merak ve Zihinsel Açıklık',
    nameEn: 'Creativity, Epistemic Curiosity & Openness',
    descriptionTr: 'Bilişsel merak boyutları (keşif ve yoksunluk), yaratıcı öz-yeterlik ve gelişim zihniyeti.',
    color: '#84CC16',
    sortOrder: 10,
    constructIds: [
      'epistemic_curiosity',
      'creative_mindset',
    ],
    facetIds: [
      'joyous_exploration_curiosity',
      'deprivation_sensitivity_curiosity',
      'creative_self_efficacy',
      'growth_mindset_intelligence',
    ],
  },
  {
    domainId: 'optional_dark_tetrad',
    code: 'optional_dark_tetrad',
    nameTr: 'İleri Düzey Modül: Subklinik Kişilik Eğilimleri',
    nameEn: 'Advanced Research Module: Subclinical Personality',
    descriptionTr: 'Kullanıcı onayıyla ölçülen subklinik Makyavelizm, Narsisizm, Psikopati ve Sadizm eğilimleri.',
    color: '#64748B',
    sortOrder: 11,
    constructIds: [
      'dark_tetrad_traits',
    ],
    facetIds: [
      'machiavellianism_subclinical',
      'grandiose_narcissism_subclinical',
      'psychopathy_subclinical',
      'everyday_sadism_subclinical',
    ],
  },
];

// -----------------------------------------------------------------------------
// 2. 37 ACTIVE MASTER CONSTRUCTS
// -----------------------------------------------------------------------------
export const MASTER_CONSTRUCTS: MasterConstructDefinition[] = [
  // Core Personality (6)
  {
    constructId: 'hexaco_honesty_humility',
    code: 'hexaco_honesty_humility',
    nameTr: 'Dürüstlük-Alçakgönüllülük',
    nameEn: 'Honesty-Humility',
    domainId: 'core_personality',
    facetIds: ['sincerity', 'fairness', 'greed_avoidance', 'modesty'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'HEXACO kuramsal faktör yapısı 4 alt boyutun ortalaması olarak hesaplanır.',
  },
  {
    constructId: 'hexaco_emotionality',
    code: 'hexaco_emotionality',
    nameTr: 'Duygusallık',
    nameEn: 'Emotionality',
    domainId: 'core_personality',
    facetIds: ['fearfulness', 'anxiety', 'dependence', 'sentimentality'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'HEXACO Duygusallık faktörü 4 alt boyutun ortalaması olarak hesaplanır.',
  },
  {
    constructId: 'hexaco_extraversion',
    code: 'hexaco_extraversion',
    nameTr: 'Dışadönüklük',
    nameEn: 'Extraversion',
    domainId: 'core_personality',
    facetIds: ['social_self_esteem', 'social_boldness', 'sociability', 'liveliness'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'HEXACO Dışadönüklük faktörü 4 alt boyutun ortalaması olarak hesaplanır.',
  },
  {
    constructId: 'hexaco_agreeableness',
    code: 'hexaco_agreeableness',
    nameTr: 'Geçimlilik (Uyumluluk)',
    nameEn: 'Agreeableness',
    domainId: 'core_personality',
    facetIds: ['forgivingness', 'gentleness', 'flexibility', 'patience'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'HEXACO Geçimlilik faktörü 4 alt boyutun ortalaması olarak hesaplanır.',
  },
  {
    constructId: 'hexaco_conscientiousness',
    code: 'hexaco_conscientiousness',
    nameTr: 'Sorumluluk',
    nameEn: 'Conscientiousness',
    domainId: 'core_personality',
    facetIds: ['organization', 'diligence', 'perfectionism', 'prudence'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'HEXACO Sorumluluk faktörü 4 alt boyutun ortalaması olarak hesaplanır.',
  },
  {
    constructId: 'hexaco_openness',
    code: 'hexaco_openness',
    nameTr: 'Deneyime Açıklık',
    nameEn: 'Openness to Experience',
    domainId: 'core_personality',
    facetIds: ['aesthetic_appreciation', 'inquisitiveness', 'creativity', 'unconventionality'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'HEXACO Açıklık faktörü 4 alt boyutun ortalaması olarak hesaplanır.',
  },

  // Self System (6)
  {
    constructId: 'core_self_esteem',
    code: 'core_self_esteem',
    nameTr: 'Genel Benlik Saygısı',
    nameEn: 'Global Self-Esteem',
    domainId: 'self_system',
    facetIds: ['core_self_esteem', 'contingent_self_worth'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Rosenberg Benlik Saygısı ve Koşullu Öz-Değer bileşeni.',
  },
  {
    constructId: 'self_compassion',
    code: 'self_compassion',
    nameTr: 'Öz-Şefkat',
    nameEn: 'Self-Compassion',
    domainId: 'self_system',
    facetIds: ['self_compassion'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Neff Öz-Şefkat tekil yapı puanı.',
  },
  {
    constructId: 'generalized_self_efficacy',
    code: 'generalized_self_efficacy',
    nameTr: 'Genel Öz-Yeterlik',
    nameEn: 'Generalized Self-Efficacy',
    domainId: 'self_system',
    facetIds: ['generalized_self_efficacy'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Schwarzer & Jerusalem Genel Öz-Yeterlik ölçeği.',
  },
  {
    constructId: 'locus_of_control',
    code: 'locus_of_control',
    nameTr: 'Denetim Odağı',
    nameEn: 'Locus of Control',
    domainId: 'self_system',
    facetIds: ['locus_of_control_internal', 'locus_of_control_external'],
    allowsDirectAggregation: false, // Internal and external are independent polarities
    scientificRationaleTr: 'İçsel ve Dışsal denetim odağı bağımsız boyutlardır; tek bir ortalamaya indirgenmez.',
  },
  {
    constructId: 'self_concept_clarity',
    code: 'self_concept_clarity',
    nameTr: 'Benlik Belirginliği',
    nameEn: 'Self-Concept Clarity',
    domainId: 'self_system',
    facetIds: ['self_concept_clarity'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Campbell Benlik Belirginliği ölçeği.',
  },
  {
    constructId: 'authenticity',
    code: 'authenticity',
    nameTr: 'Otantiklik',
    nameEn: 'Authenticity',
    domainId: 'self_system',
    facetIds: ['authenticity'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Wood vd. Otantiklik ölçeği.',
  },

  // Emotion Regulation (5)
  {
    constructId: 'cognitive_reappraisal',
    code: 'cognitive_reappraisal',
    nameTr: 'Bilişsel Yeniden Değerlendirme',
    nameEn: 'Cognitive Reappraisal',
    domainId: 'emotion_regulation',
    facetIds: ['cognitive_reappraisal'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Gross ERQ Bilişsel Yeniden Değerlendirme alt ölçeği.',
  },
  {
    constructId: 'expressive_suppression',
    code: 'expressive_suppression',
    nameTr: 'Duygusal Baskılama',
    nameEn: 'Expressive Suppression',
    domainId: 'emotion_regulation',
    facetIds: ['expressive_suppression'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Gross ERQ Duygusal Baskılama alt ölçeği.',
  },
  {
    constructId: 'affective_tone',
    code: 'affective_tone',
    nameTr: 'Mizaç Duygulanımı (PANAS)',
    nameEn: 'Trait Affective Tone',
    domainId: 'emotion_regulation',
    facetIds: ['positive_affect_trait', 'negative_affect_trait', 'affect_intensity'],
    allowsDirectAggregation: false, // Positive and negative affect are orthogonal
    scientificRationaleTr: 'Pozitif ve Negatif duygulanım ortogonal boyutlardır; tek bir toplama indirgenemez.',
  },
  {
    constructId: 'distress_tolerance',
    code: 'distress_tolerance',
    nameTr: 'Sıkıntı Toleransı ve Kabul',
    nameEn: 'Distress Tolerance & Acceptance',
    domainId: 'emotion_regulation',
    facetIds: ['distress_tolerance', 'experiential_avoidance'],
    allowsDirectAggregation: false,
    scientificRationaleTr: 'Sıkıntı toleransı ve yaşantısal kaçınma örüntü düzeyinde incelenir.',
  },
  {
    constructId: 'self_conscious_emotions',
    code: 'self_conscious_emotions',
    nameTr: 'Öz-Bilinçli Duygular (Utanç ve Suçluluk)',
    nameEn: 'Self-Conscious Emotions',
    domainId: 'emotion_regulation',
    facetIds: ['shame_proneness', 'guilt_proneness'],
    allowsDirectAggregation: false, // Shame and guilt are clinically/functionally distinct
    scientificRationaleTr: 'Utanç ve suçluluk eğilimi farklı işlevsel dinamiklerdir.',
  },

  // Cognition & Decision (4)
  {
    constructId: 'epistemic_drive',
    code: 'epistemic_drive',
    nameTr: 'Bilişsel Motivasyon ve Belirsizlik Kapatma',
    nameEn: 'Epistemic Drive & Closure',
    domainId: 'cognition_decision',
    facetIds: ['need_for_cognition', 'need_for_cognitive_closure'],
    allowsDirectAggregation: false,
    scientificRationaleTr: 'Biliş ihtiyacı ve bilişsel kapanma ihtiyacı bağımsız bilişsel motivasyonlardır.',
  },
  {
    constructId: 'thinking_styles',
    code: 'thinking_styles',
    nameTr: 'İkili Süreç Düşünme Tarzları (REI)',
    nameEn: 'Dual-Process Thinking Styles',
    domainId: 'cognition_decision',
    facetIds: ['rational_analytical_thinking', 'intuitive_experiential_thinking'],
    allowsDirectAggregation: false,
    scientificRationaleTr: 'Rasyonel ve sezgisel düşünme bağımsız iki bilişsel sistemdir.',
  },
  {
    constructId: 'cognitive_adaptability',
    code: 'cognitive_adaptability',
    nameTr: 'Bilişsel Esneklik ve Belirsizliğe Tahammül',
    nameEn: 'Cognitive Adaptability & Uncertainty',
    domainId: 'cognition_decision',
    facetIds: ['cognitive_flexibility', 'intolerance_of_uncertainty', 'rumination_brooding'],
    allowsDirectAggregation: false,
    scientificRationaleTr: 'Bilişsel esneklik, belirsizlik tahammülsüzlüğü ve ruminasyon bağımsız örüntülerdir.',
  },
  {
    constructId: 'decision_orientation',
    code: 'decision_orientation',
    nameTr: 'Karar Yönelimi ve Erteleme',
    nameEn: 'Decision Orientation',
    domainId: 'cognition_decision',
    facetIds: ['decision_style_maximizing', 'procrastination_tendency'],
    allowsDirectAggregation: false,
    scientificRationaleTr: 'Maksimize edici karar tarzı ve erteleme eğilimi profil örüntüsü olarak incelenir.',
  },

  // Self Regulation (2)
  {
    constructId: 'impulsivity_uppsp',
    code: 'impulsivity_uppsp',
    nameTr: 'Çok Boyutlu Dürtüsellik (UPPS-P)',
    nameEn: 'Multidimensional Impulsivity (UPPS-P)',
    domainId: 'self_regulation',
    facetIds: [
      'uppsp_negative_urgency',
      'uppsp_positive_urgency',
      'uppsp_lack_of_premeditation',
      'uppsp_lack_of_perseverance',
      'uppsp_sensation_seeking',
    ],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'UPPS-P 5 alt boyutun ortalaması genel dürtüsellik bileşeni olarak raporlanabilir.',
  },
  {
    constructId: 'volitional_stamina',
    code: 'volitional_stamina',
    nameTr: 'İrade Gücü ve Öz-Kontrol',
    nameEn: 'Volitional Stamina & Self-Control',
    domainId: 'self_regulation',
    facetIds: ['general_self_control', 'delay_discounting_preference', 'long_term_grit'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Genel öz-kontrol, erteleme ve azim ortak irade kapasitesini temsil eder.',
  },

  // Motivation & Values (3)
  {
    constructId: 'basic_psychological_needs',
    code: 'basic_psychological_needs',
    nameTr: 'Temel Psikolojik İhtiyaçlar (Öz-Belirleme)',
    nameEn: 'Basic Psychological Needs (SDT)',
    domainId: 'motivation_values',
    facetIds: ['autonomy_need_satisfaction', 'competence_need_satisfaction', 'relatedness_need_satisfaction'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Özerklik, yetkinlik ve ilişkisellik ihtiyaç doyumu genel ihtiyaç doyum ortalaması olarak özetlenebilir.',
  },
  {
    constructId: 'universal_values',
    code: 'universal_values',
    nameTr: 'Evrensel İnsan Değerleri (Schwartz)',
    nameEn: 'Universal Human Values (Schwartz)',
    domainId: 'motivation_values',
    facetIds: [
      'schwartz_openness_to_change',
      'schwartz_self_transcendence',
      'schwartz_conservation',
      'schwartz_self_enhancement',
    ],
    allowsDirectAggregation: false, // Schwartz values circumplex represents trade-offs, not single sum
    scientificRationaleTr: 'Schwartz değer dairesi zıt değer yönelimleri içerir; tek bir ortalamaya indirgenemez.',
  },
  {
    constructId: 'existential_meaning',
    code: 'existential_meaning',
    nameTr: 'Varoluşsal Anlam ve Amaç',
    nameEn: 'Existential Meaning & Purpose',
    domainId: 'motivation_values',
    facetIds: ['presence_of_meaning', 'search_for_meaning'],
    allowsDirectAggregation: false, // Presence vs Search of meaning are distinct orthogonal dimensions
    scientificRationaleTr: 'Anlam varlığı ve anlam arayışı Steger kuramında bağımsız eksenlerdir.',
  },

  // Social & Relational (4)
  {
    constructId: 'attachment_system',
    code: 'attachment_system',
    nameTr: 'Yetişkin Bağlanma Boyutları (ECR)',
    nameEn: 'Adult Attachment Dimensions',
    domainId: 'social_relational',
    facetIds: ['attachment_anxiety', 'attachment_avoidance'],
    allowsDirectAggregation: false, // Attachment anxiety and avoidance define a 2D coordinate space
    scientificRationaleTr: 'Bağlanma kaygısı ve kaçınması 2 boyutlu koordinat uzayı tanımlar; ortalamaya indirgenmez.',
  },
  {
    constructId: 'multidimensional_empathy',
    code: 'multidimensional_empathy',
    nameTr: 'Çok Boyutlu Empati (IRI)',
    nameEn: 'Multidimensional Empathy (IRI)',
    domainId: 'social_relational',
    facetIds: ['cognitive_perspective_taking', 'empathic_concern'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Bilişsel bakış açısı alma ve duygusal duyarlık toplam empati eğilimi olarak hesaplanabilir.',
  },
  {
    constructId: 'social_agency_boundaries',
    code: 'social_agency_boundaries',
    nameTr: 'Sosyal İrade ve İlişkisel Sınırlar',
    nameEn: 'Social Agency & Relational Boundaries',
    domainId: 'social_relational',
    facetIds: ['assertiveness', 'social_connectedness', 'rejection_sensitivity_nonclinical'],
    allowsDirectAggregation: false,
    scientificRationaleTr: 'Atılganlık, sosyal bağlılık ve reddedilme duyarlılığı bağımsız ilişkisel dinamiklerdir.',
  },
  {
    constructId: 'conflict_styles',
    code: 'conflict_styles',
    nameTr: 'Çatışma Çözme Stilleri',
    nameEn: 'Conflict Resolution Styles',
    domainId: 'social_relational',
    facetIds: ['cooperation_orientation', 'conflict_avoidance'],
    allowsDirectAggregation: false,
    scientificRationaleTr: 'İşbirliği ve kaçınma çatışma durumlarında farklı stratejilerdir.',
  },

  // Wellbeing & Vitality (2)
  {
    constructId: 'psychological_flourishing',
    code: 'psychological_flourishing',
    nameTr: 'Psikolojik Gelişme ve Canlılık',
    nameEn: 'Psychological Flourishing & Vitality',
    domainId: 'wellbeing_vitality',
    facetIds: ['flourishing_scale', 'subjective_vitality'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Diener Gelişme ve Ryan Canlılık boyutları öznel iyi oluşu temsil eder.',
  },
  {
    constructId: 'life_satisfaction',
    code: 'life_satisfaction',
    nameTr: 'Yaşam Doyumu',
    nameEn: 'Life Satisfaction',
    domainId: 'wellbeing_vitality',
    facetIds: ['satisfaction_with_life'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Diener Yaşam Doyumu ölçeği tekil yapı puanıdır.',
  },

  // Coping & Resilience (2)
  {
    constructId: 'psychological_resilience',
    code: 'psychological_resilience',
    nameTr: 'Psikolojik Sağlamlık ve Toparlanma',
    nameEn: 'Ego-Resilience & Recovery',
    domainId: 'coping_resilience',
    facetIds: ['ego_resilience', 'stress_recovery'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Ego sağlamlığı ve stres sonrası toparlanma genel psikolojik dayanıklılığı oluşturur.',
  },
  {
    constructId: 'coping_orientations',
    code: 'coping_orientations',
    nameTr: 'Çok Boyutlu Başa Çıkma (Brief COPE)',
    nameEn: 'Multidimensional Coping',
    domainId: 'coping_resilience',
    facetIds: ['problem_focused_coping', 'emotion_focused_coping'],
    allowsDirectAggregation: false,
    scientificRationaleTr: 'Problem odaklı ve duygu odaklı başa çıkma farklı bağlamsal stratejilerdir.',
  },

  // Creativity & Curiosity (2)
  {
    constructId: 'epistemic_curiosity',
    code: 'epistemic_curiosity',
    nameTr: 'Bilişsel Merak Boyutları (5DCR)',
    nameEn: 'Epistemic Curiosity',
    domainId: 'creativity_curiosity',
    facetIds: ['joyous_exploration_curiosity', 'deprivation_sensitivity_curiosity'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Keşif ve yoksunluk merakı Kashdan 5DCR kuramında genel bilişsel merakı oluşturur.',
  },
  {
    constructId: 'creative_mindset',
    code: 'creative_mindset',
    nameTr: 'Yaratıcı Öz-Yeterlik ve Gelişim Zihniyeti',
    nameEn: 'Creative Self-Efficacy & Growth Mindset',
    domainId: 'creativity_curiosity',
    facetIds: ['creative_self_efficacy', 'growth_mindset_intelligence'],
    allowsDirectAggregation: true,
    scientificRationaleTr: 'Yaratıcı öz-inanç ve Dweck gelişim zihniyeti yaratıcı potansiyeli destekler.',
  },

  // Dark Tetrad (1)
  {
    constructId: 'dark_tetrad_traits',
    code: 'dark_tetrad_traits',
    nameTr: 'Kısa Karanlık Dörtlü (SD4 - Subklinik)',
    nameEn: 'Short Dark Tetrad (SD4)',
    domainId: 'optional_dark_tetrad',
    facetIds: [
      'machiavellianism_subclinical',
      'grandiose_narcissism_subclinical',
      'psychopathy_subclinical',
      'everyday_sadism_subclinical',
    ],
    allowsDirectAggregation: false, // Distinct subclinical constructs
    scientificRationaleTr: 'Karanlık Dörtlü özellikleri bağımsız subklinik boyutlar olarak profil bazında incelenir.',
  },
];

// -----------------------------------------------------------------------------
// 3. 91 MASTER FACETS (Alphabetical / Domain Order)
// -----------------------------------------------------------------------------
export const MASTER_FACETS: MasterFacetDefinition[] = [
  // --- Core Personality: Honesty-Humility (4) ---
  {
    facetId: 'sincerity',
    code: 'sincerity',
    nameTr: 'İçtenlik',
    nameEn: 'Sincerity',
    domainId: 'core_personality',
    constructId: 'hexaco_honesty_humility',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kişilerarası ilişkilerde dürüst ve yapmacıksız olma; manipülasyondan kaçınma eğilimi.',
  },
  {
    facetId: 'fairness',
    code: 'fairness',
    nameTr: 'Adillik',
    nameEn: 'Fairness',
    domainId: 'core_personality',
    constructId: 'hexaco_honesty_humility',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Hile, rüşvet ve kuralları kişisel çıkar için esnetmekten kaçınma eğilimi.',
  },
  {
    facetId: 'greed_avoidance',
    code: 'greed_avoidance',
    nameTr: 'Açgözlülükten Kaçınma',
    nameEn: 'Greed Avoidance',
    domainId: 'core_personality',
    constructId: 'hexaco_honesty_humility',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Aşırı lüks, zenginlik gösterişi ve sosyal statü sembollerine karşı kayıtsızlık.',
  },
  {
    facetId: 'modesty',
    code: 'modesty',
    nameTr: 'Alçakgönüllülük',
    nameEn: 'Modesty',
    domainId: 'core_personality',
    constructId: 'hexaco_honesty_humility',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kendini diğer insanlardan üstün görmeme ve ayrıcalık beklememe eğilimi.',
  },

  // --- Core Personality: Emotionality (4) ---
  {
    facetId: 'fearfulness',
    code: 'fearfulness',
    nameTr: 'Korku / Tehlike Duyarlılığı',
    nameEn: 'Fearfulness',
    domainId: 'core_personality',
    constructId: 'hexaco_emotionality',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Fiziksel tehlikelerden ve yaralanma riskinden kaçınma eğilimi.',
  },
  {
    facetId: 'anxiety',
    code: 'anxiety',
    nameTr: 'Kaygı Eğilimi',
    nameEn: 'Anxiety',
    domainId: 'core_personality',
    constructId: 'hexaco_emotionality',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Stresli durumlarda ve belirsizlik karşısında endişelenme eğilimi.',
  },
  {
    facetId: 'dependence',
    code: 'dependence',
    nameTr: 'Bağımlılık (Duygusal Destek İhtiyacı)',
    nameEn: 'Dependence',
    domainId: 'core_personality',
    constructId: 'hexaco_emotionality',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Zor zamanlarda başkalarından duygusal destek ve güvence arama eğilimi.',
  },
  {
    facetId: 'sentimentality',
    code: 'sentimentality',
    nameTr: 'Duygusallık / Empatik Hassasiyet',
    nameEn: 'Sentimentality',
    domainId: 'core_personality',
    constructId: 'hexaco_emotionality',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Güçlü duygusal bağlar kurma ve başkalarının duygularından derin etkilenme.',
  },

  // --- Core Personality: Extraversion (4) ---
  {
    facetId: 'social_self_esteem',
    code: 'social_self_esteem',
    nameTr: 'Sosyal Özsaygı',
    nameEn: 'Social Self-Esteem',
    domainId: 'core_personality',
    constructId: 'hexaco_extraversion',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Sosyal ortamlarda kendini değerli, kabul görmüş ve popüler hissetme.',
  },
  {
    facetId: 'social_boldness',
    code: 'social_boldness',
    nameTr: 'Sosyal Cesaret / Girişkenlik',
    nameEn: 'Social Boldness',
    domainId: 'core_personality',
    constructId: 'hexaco_extraversion',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Topluluk önünde konuşma ve tanımadığı ortamlarda rahatça inisiyatif alma.',
  },
  {
    facetId: 'sociability',
    code: 'sociability',
    nameTr: 'Sosyallik / İletişim İsteği',
    nameEn: 'Sociability',
    domainId: 'core_personality',
    constructId: 'hexaco_extraversion',
    expectedItemCount: 5,
    scientificDefinitionTr: 'İnsanlarla etkileşimde bulunmaktan, sohbet etmekten ve partilerden keyif alma.',
  },
  {
    facetId: 'liveliness',
    code: 'liveliness',
    nameTr: 'Canlılık / Enerji',
    nameEn: 'Liveliness',
    domainId: 'core_personality',
    constructId: 'hexaco_extraversion',
    expectedItemCount: 5,
    scientificDefinitionTr: 'İyimserlik, yüksek enerji ve coşkulu bir mizaç sergileme.',
  },

  // --- Core Personality: Agreeableness (4) ---
  {
    facetId: 'forgivingness',
    code: 'forgivingness',
    nameTr: 'Bağışlayıcılık',
    nameEn: 'Forgivingness',
    domainId: 'core_personality',
    constructId: 'hexaco_agreeableness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kendisine haksızlık eden kişilere kin gütmeme ve güveni yeniden kurabilme.',
  },
  {
    facetId: 'gentleness',
    code: 'gentleness',
    nameTr: 'Naziklik / Hoşgörü',
    nameEn: 'Gentleness',
    domainId: 'core_personality',
    constructId: 'hexaco_agreeableness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'İnsanlara karşı sert eleştirilerden kaçınma, yapıcı ve nazik yaklaşma.',
  },
  {
    facetId: 'flexibility',
    code: 'flexibility',
    nameTr: 'Esneklik / Uzlaşmacılık',
    nameEn: 'Flexibility',
    domainId: 'core_personality',
    constructId: 'hexaco_agreeableness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Fikir ayrılıklarında uzlaşmaya açık olma ve inatçılıktan kaçınma.',
  },
  {
    facetId: 'patience',
    code: 'patience',
    nameTr: 'Sabır / Sakinlik',
    nameEn: 'Patience',
    domainId: 'core_personality',
    constructId: 'hexaco_agreeableness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Öfke kontrolü ve kışkırtıcı durumlarda sakin kalabilme kapasitesi.',
  },

  // --- Core Personality: Conscientiousness (4) ---
  {
    facetId: 'organization',
    code: 'organization',
    nameTr: 'Düzenlilik / Tertip',
    nameEn: 'Organization',
    domainId: 'core_personality',
    constructId: 'hexaco_conscientiousness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Çevresini ve işlerini düzenli tutma, planlı ve sistemli hareket etme.',
  },
  {
    facetId: 'diligence',
    code: 'diligence',
    nameTr: 'Çalışkanlık / Azim',
    nameEn: 'Diligence',
    domainId: 'core_personality',
    constructId: 'hexaco_conscientiousness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Zorlu görevlerde pes etmeden çalışma ve güçlü bir çalışma etiği sergileme.',
  },
  {
    facetId: 'perfectionism',
    code: 'perfectionism',
    nameTr: 'Kusursuzluk Arayışı / Özen',
    nameEn: 'Perfectionism',
    domainId: 'core_personality',
    constructId: 'hexaco_conscientiousness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Hataları önceden fark etme, ayrıntılara dikkat etme ve işi titizlikle tamamlama.',
  },
  {
    facetId: 'prudence',
    code: 'prudence',
    nameTr: 'İhtiyatlılık / Tedbirlilik',
    nameEn: 'Prudence',
    domainId: 'core_personality',
    constructId: 'hexaco_conscientiousness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Düşünmeden hareket etmekten kaçınma, kararların sonuçlarını tartma.',
  },

  // --- Core Personality: Openness to Experience (4) ---
  {
    facetId: 'aesthetic_appreciation',
    code: 'aesthetic_appreciation',
    nameTr: 'Estetik Takdir / Sanatsal İlgi',
    nameEn: 'Aesthetic Appreciation',
    domainId: 'core_personality',
    constructId: 'hexaco_openness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Sanata, doğa güzelliklerine ve estetik deneyimlere karşı duyarlılık.',
  },
  {
    facetId: 'inquisitiveness',
    code: 'inquisitiveness',
    nameTr: 'Araştırmacılık / Entelektüel Merak',
    nameEn: 'Inquisitiveness',
    domainId: 'core_personality',
    constructId: 'hexaco_openness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Farklı bilgi alanlarını, bilimsel ve felsefi konuları öğrenme merakı.',
  },
  {
    facetId: 'creativity',
    code: 'creativity',
    nameTr: 'Yaratıcılık / Özgün Fikirler',
    nameEn: 'Creativity',
    domainId: 'core_personality',
    constructId: 'hexaco_openness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yeni ve alışılmışın dışında fikirler üretme, problem çözmede yenilikçilik.',
  },
  {
    facetId: 'unconventionality',
    code: 'unconventionality',
    nameTr: 'Kalıpların Dışına Çıkma',
    nameEn: 'Unconventionality',
    domainId: 'core_personality',
    constructId: 'hexaco_openness',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Geleneksel olmayan yaklaşımları benimseme ve farklı bakış açılarına açıklık.',
  },

  // --- Self-System (8) ---
  {
    facetId: 'core_self_esteem',
    code: 'core_self_esteem',
    nameTr: 'Temel Benlik Saygısı (RSES)',
    nameEn: 'Core Self-Esteem',
    domainId: 'self_system',
    constructId: 'core_self_esteem',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Bireyin kendini genel olarak değerli ve saygıya layık bir insan olarak algılaması.',
  },
  {
    facetId: 'contingent_self_worth',
    code: 'contingent_self_worth',
    nameTr: 'Koşullu Öz-Değer Algısı',
    nameEn: 'Contingent Self-Worth',
    domainId: 'self_system',
    constructId: 'core_self_esteem',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Öz-değer hissinin dışsal başarı ve onaylanmaya bağlılık derecesi.',
  },
  {
    facetId: 'self_compassion',
    code: 'self_compassion',
    nameTr: 'Öz-Şefkat (Neff)',
    nameEn: 'Self-Compassion',
    domainId: 'self_system',
    constructId: 'self_compassion',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Zorluk ve başarısızlık anlarında kendine karşı anlayışlı ve şefkatli olabilme.',
  },
  {
    facetId: 'generalized_self_efficacy',
    code: 'generalized_self_efficacy',
    nameTr: 'Genel Öz-Yeterlik (GSE)',
    nameEn: 'Generalized Self-Efficacy',
    domainId: 'self_system',
    constructId: 'generalized_self_efficacy',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Karşılaşılan yeni veya zorlu durumların üstesinden gelebileceğine olan inanç.',
  },
  {
    facetId: 'locus_of_control_internal',
    code: 'locus_of_control_internal',
    nameTr: 'İçsel Denetim Odağı',
    nameEn: 'Internal Locus of Control',
    domainId: 'self_system',
    constructId: 'locus_of_control',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yaşam olaylarının ve sonuçlarının kendi eylem ve kararlarına bağlı olduğu inancı.',
  },
  {
    facetId: 'locus_of_control_external',
    code: 'locus_of_control_external',
    nameTr: 'Dışsal Denetim Odağı',
    nameEn: 'External Locus of Control',
    domainId: 'self_system',
    constructId: 'locus_of_control',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yaşam olaylarının şans, kader veya güçlü diğer insanlara bağlı olduğu inancı.',
  },
  {
    facetId: 'self_concept_clarity',
    code: 'self_concept_clarity',
    nameTr: 'Benlik Belirginliği (SCC)',
    nameEn: 'Self-Concept Clarity',
    domainId: 'self_system',
    constructId: 'self_concept_clarity',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Benlik algısının netliği, içsel tutarlılığı ve zaman içindeki kararlılığı.',
  },
  {
    facetId: 'authenticity',
    code: 'authenticity',
    nameTr: 'Otantik Yaşama / Özgünlük',
    nameEn: 'Authenticity',
    domainId: 'self_system',
    constructId: 'authenticity',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kendi değerleriyle uyumlu yaşama ve dışsal baskılarla sahte rollere girmeme.',
  },

  // --- Emotion Regulation (9) ---
  {
    facetId: 'cognitive_reappraisal',
    code: 'cognitive_reappraisal',
    nameTr: 'Bilişsel Yeniden Değerlendirme (ERQ)',
    nameEn: 'Cognitive Reappraisal',
    domainId: 'emotion_regulation',
    constructId: 'cognitive_reappraisal',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Olayların anlamını değiştirerek duygusal etkiyi yapıcı şekilde düzenleme.',
  },
  {
    facetId: 'expressive_suppression',
    code: 'expressive_suppression',
    nameTr: 'Duygusal Baskılama (ERQ)',
    nameEn: 'Expressive Suppression',
    domainId: 'emotion_regulation',
    constructId: 'expressive_suppression',
    expectedItemCount: 5,
    scientificDefinitionTr: 'İçsel duygusal tepkileri dışarı yansıtmama ve duyguları bastırma eğilimi.',
  },
  {
    facetId: 'positive_affect_trait',
    code: 'positive_affect_trait',
    nameTr: 'Mizaç Pozitif Duygulanımı (PANAS-PA)',
    nameEn: 'Trait Positive Affect',
    domainId: 'emotion_regulation',
    constructId: 'affective_tone',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Bireyin genel olarak coşkulu, enerjik ve dikkatli hissetme sıklığı.',
  },
  {
    facetId: 'negative_affect_trait',
    code: 'negative_affect_trait',
    nameTr: 'Mizaç Negatif Duygulanımı (PANAS-NA)',
    nameEn: 'Trait Negative Affect',
    domainId: 'emotion_regulation',
    constructId: 'affective_tone',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Bireyin genel olarak kaygılı, gergin veya sıkıntılı hissetme sıklığı.',
  },
  {
    facetId: 'affect_intensity',
    code: 'affect_intensity',
    nameTr: 'Duygulanım Yoğunluğu (AIM)',
    nameEn: 'Affect Intensity',
    domainId: 'emotion_regulation',
    constructId: 'affective_tone',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Duyguların yaşanan şiddeti ve fizyolojik/öznel etki derinliği.',
  },
  {
    facetId: 'distress_tolerance',
    code: 'distress_tolerance',
    nameTr: 'Sıkıntı Toleransı (DTS)',
    nameEn: 'Distress Tolerance',
    domainId: 'emotion_regulation',
    constructId: 'distress_tolerance',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Olumsuz duygu durumlarına ve psikolojik baskıya dayanabilme kapasitesi.',
  },
  {
    facetId: 'experiential_avoidance',
    code: 'experiential_avoidance',
    nameTr: 'Yaşantısal Kaçınma (AAQ-2)',
    nameEn: 'Experiential Avoidance',
    domainId: 'emotion_regulation',
    constructId: 'distress_tolerance',
    expectedItemCount: 5,
    scientificDefinitionTr: 'İstenmeyen içsel düşünce ve duygulardan kaçınma veya bunları bastırma çabası.',
  },
  {
    facetId: 'shame_proneness',
    code: 'shame_proneness',
    nameTr: 'Utanç Eğilimi (TOSCA)',
    nameEn: 'Shame Proneness',
    domainId: 'emotion_regulation',
    constructId: 'self_conscious_emotions',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Hata veya başarısızlık durumunda benliğin bütününü kusurlu hissetme eğilimi.',
  },
  {
    facetId: 'guilt_proneness',
    code: 'guilt_proneness',
    nameTr: 'Suçluluk Eğilimi / Telafi Arzusu (TOSCA)',
    nameEn: 'Guilt Proneness',
    domainId: 'emotion_regulation',
    constructId: 'self_conscious_emotions',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yapılan eylemin sorumluluğunu üstlenme ve yapıcı telafi davranışı gösterme.',
  },

  // --- Cognition & Decision (9) ---
  {
    facetId: 'need_for_cognition',
    code: 'need_for_cognition',
    nameTr: 'Biliş İhtiyacı (NFC)',
    nameEn: 'Need for Cognition',
    domainId: 'cognition_decision',
    constructId: 'epistemic_drive',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Zihinsel çaba gerektiren karmaşık sorunlar üzerine düşünmekten keyif alma.',
  },
  {
    facetId: 'need_for_cognitive_closure',
    code: 'need_for_cognitive_closure',
    nameTr: 'Bilişsel Kapanma İhtiyacı (NFCS)',
    nameEn: 'Need for Cognitive Closure',
    domainId: 'cognition_decision',
    constructId: 'epistemic_drive',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Belirsizlikten rahatsız olma ve hızlı net cevaplara ulaşma arzusu.',
  },
  {
    facetId: 'rational_analytical_thinking',
    code: 'rational_analytical_thinking',
    nameTr: 'Rasyonel ve Analitik Düşünme (REI-R)',
    nameEn: 'Rational Thinking Style',
    domainId: 'cognition_decision',
    constructId: 'thinking_styles',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kararlarda mantıksal analiz, kanıt ve sistematik düşünceye güvenme.',
  },
  {
    facetId: 'intuitive_experiential_thinking',
    code: 'intuitive_experiential_thinking',
    nameTr: 'Sezgisel ve Deneyimsel Düşünme (REI-E)',
    nameEn: 'Intuitive Thinking Style',
    domainId: 'cognition_decision',
    constructId: 'thinking_styles',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kararlarda içgüdülere, ilk hislere ve sezgisel ipuçlarına güvenme.',
  },
  {
    facetId: 'cognitive_flexibility',
    code: 'cognitive_flexibility',
    nameTr: 'Bilişsel Esneklik (CFI)',
    nameEn: 'Cognitive Flexibility',
    domainId: 'cognition_decision',
    constructId: 'cognitive_adaptability',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Değişen koşullara göre düşünce stratejilerini adapte edebilme yetisi.',
  },
  {
    facetId: 'intolerance_of_uncertainty',
    code: 'intolerance_of_uncertainty',
    nameTr: 'Belirsizliğe Tahammülsüzlük (IUS)',
    nameEn: 'Intolerance of Uncertainty',
    domainId: 'cognition_decision',
    constructId: 'cognitive_adaptability',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Gelecekteki belirsizlikleri tehdit edici ve kabul edilemez algılama.',
  },
  {
    facetId: 'rumination_brooding',
    code: 'rumination_brooding',
    nameTr: 'Bilişsel Ruminasyon (RRS)',
    nameEn: 'Rumination & Brooding',
    domainId: 'cognition_decision',
    constructId: 'cognitive_adaptability',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Geçmiş hatalar ve olumsuz durumlar üzerine tekrarlayıcı ve verimsiz düşünme.',
  },
  {
    facetId: 'decision_style_maximizing',
    code: 'decision_style_maximizing',
    nameTr: 'Maksimize Edici Karar Tarzı',
    nameEn: 'Maximizing Decision Style',
    domainId: 'cognition_decision',
    constructId: 'decision_orientation',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Her kararda en mükemmel seçeneği bulma çabası ve doyumsuzluk riski.',
  },
  {
    facetId: 'procrastination_tendency',
    code: 'procrastination_tendency',
    nameTr: 'Erteleme Eğilimi (GPS)',
    nameEn: 'Procrastination Tendency',
    domainId: 'cognition_decision',
    constructId: 'decision_orientation',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Önemli görevleri başlatmayı veya bitirmeyi gereksiz yere geciktirme.',
  },

  // --- Self Regulation (8) ---
  {
    facetId: 'uppsp_negative_urgency',
    code: 'uppsp_negative_urgency',
    nameTr: 'Negatif Aciliyet (UPPS-P)',
    nameEn: 'Negative Urgency',
    domainId: 'self_regulation',
    constructId: 'impulsivity_uppsp',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yoğun olumsuz duygu anlarında düşünmeden dürtüsel hareket etme eğilimi.',
  },
  {
    facetId: 'uppsp_positive_urgency',
    code: 'uppsp_positive_urgency',
    nameTr: 'Pozitif Aciliyet (UPPS-P)',
    nameEn: 'Positive Urgency',
    domainId: 'self_regulation',
    constructId: 'impulsivity_uppsp',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Aşırı sevinç ve coşku anlarında riskli/dürtüsel kararlar alma eğilimi.',
  },
  {
    facetId: 'uppsp_lack_of_premeditation',
    code: 'uppsp_lack_of_premeditation',
    nameTr: 'Önceden Düşünmeme (UPPS-P)',
    nameEn: 'Lack of Premeditation',
    domainId: 'self_regulation',
    constructId: 'impulsivity_uppsp',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Eyleme geçmeden önce sonuçları tartmama ve plan yapmama eğilimi.',
  },
  {
    facetId: 'uppsp_lack_of_perseverance',
    code: 'uppsp_lack_of_perseverance',
    nameTr: 'Sebatsızlık (UPPS-P)',
    nameEn: 'Lack of Perseverance',
    domainId: 'self_regulation',
    constructId: 'impulsivity_uppsp',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Sıkıcı veya zor görevlerde dikkatin dağılması ve görevi yarıda bırakma.',
  },
  {
    facetId: 'uppsp_sensation_seeking',
    code: 'uppsp_sensation_seeking',
    nameTr: 'Heyecan Arayışı (UPPS-P)',
    nameEn: 'Sensation Seeking',
    domainId: 'self_regulation',
    constructId: 'impulsivity_uppsp',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yeni, yoğun ve heyecan verici deneyimler yaşama isteği.',
  },
  {
    facetId: 'general_self_control',
    code: 'general_self_control',
    nameTr: 'Genel Öz-Kontrol (BSCS)',
    nameEn: 'General Self-Control',
    domainId: 'self_regulation',
    constructId: 'volitional_stamina',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Anlık dürtüleri bastırma ve uzun vadeli hedefler doğrultusunda odaklanma.',
  },
  {
    facetId: 'delay_discounting_preference',
    code: 'delay_discounting_preference',
    nameTr: 'Gecikmiş Doyum Tercihi',
    nameEn: 'Delay of Gratification',
    domainId: 'self_regulation',
    constructId: 'volitional_stamina',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Gelecekteki daha büyük kazanımlar için anlık hazlardan vazgeçebilme.',
  },
  {
    facetId: 'long_term_grit',
    code: 'long_term_grit',
    nameTr: 'Uzun Vadeli Azim (Grit)',
    nameEn: 'Long-Term Grit',
    domainId: 'self_regulation',
    constructId: 'volitional_stamina',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yıllar süren uzun vadeli hedeflere tutku ve kararlılıkla bağlı kalabilme.',
  },

  // --- Motivation & Values (9) ---
  {
    facetId: 'autonomy_need_satisfaction',
    code: 'autonomy_need_satisfaction',
    nameTr: 'Özerklik İhtiyaç Doyumu (BPNS)',
    nameEn: 'Autonomy Need Satisfaction',
    domainId: 'motivation_values',
    constructId: 'basic_psychological_needs',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kişinin kendi kararlarını özgürce aldığı ve iradesini yansıttığı hissi.',
  },
  {
    facetId: 'competence_need_satisfaction',
    code: 'competence_need_satisfaction',
    nameTr: 'Yetkinlik İhtiyaç Doyumu (BPNS)',
    nameEn: 'Competence Need Satisfaction',
    domainId: 'motivation_values',
    constructId: 'basic_psychological_needs',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kişinin yaptığı işlerde ustalaştığı ve etkili sonuçlar ürettiği hissi.',
  },
  {
    facetId: 'relatedness_need_satisfaction',
    code: 'relatedness_need_satisfaction',
    nameTr: 'İlişkisellik İhtiyaç Doyumu (BPNS)',
    nameEn: 'Relatedness Need Satisfaction',
    domainId: 'motivation_values',
    constructId: 'basic_psychological_needs',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Diğer insanlarla samimi, güvenli ve karşılıklı bağ kurabilme hissi.',
  },
  {
    facetId: 'schwartz_openness_to_change',
    code: 'schwartz_openness_to_change',
    nameTr: 'Değişime Açıklık (Schwartz)',
    nameEn: 'Openness to Change',
    domainId: 'motivation_values',
    constructId: 'universal_values',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Öz-yönelim ve uyarılım değerleri; bağımsız düşünce ve yenilik arayışı.',
  },
  {
    facetId: 'schwartz_self_transcendence',
    code: 'schwartz_self_transcendence',
    nameTr: 'Öz-Aşkınlık (Schwartz)',
    nameEn: 'Self-Transcendence',
    domainId: 'motivation_values',
    constructId: 'universal_values',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Evrenselcilik ve yardımseverlik değerleri; başkalarının ve doğanın esenliği.',
  },
  {
    facetId: 'schwartz_conservation',
    code: 'schwartz_conservation',
    nameTr: 'Muhafazacılık / Düzen (Schwartz)',
    nameEn: 'Conservation Values',
    domainId: 'motivation_values',
    constructId: 'universal_values',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Güvenlik, uyma ve gelenek değerleri; toplumsal istikrar ve düzeni koruma.',
  },
  {
    facetId: 'schwartz_self_enhancement',
    code: 'schwartz_self_enhancement',
    nameTr: 'Öz-Genişletme (Schwartz)',
    nameEn: 'Self-Enhancement',
    domainId: 'motivation_values',
    constructId: 'universal_values',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Güç ve başarı değerleri; sosyal statü, prestij ve kişisel başarı arayışı.',
  },
  {
    facetId: 'presence_of_meaning',
    code: 'presence_of_meaning',
    nameTr: 'Anlam Varlığı (MLQ-P)',
    nameEn: 'Presence of Meaning',
    domainId: 'motivation_values',
    constructId: 'existential_meaning',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yaşamın bir amaca sahip olduğunu ve derin bir anlam taşıdığını hissetme.',
  },
  {
    facetId: 'search_for_meaning',
    code: 'search_for_meaning',
    nameTr: 'Anlam Arayışı (MLQ-S)',
    nameEn: 'Search for Meaning',
    domainId: 'motivation_values',
    constructId: 'existential_meaning',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yaşamını anlamlandırma ve varoluşsal amaçlar keşfetme yönelimi.',
  },

  // --- Social & Relational (9) ---
  {
    facetId: 'attachment_anxiety',
    code: 'attachment_anxiety',
    nameTr: 'Bağlanma Kaygısı (ECR-R)',
    nameEn: 'Attachment Anxiety',
    domainId: 'social_relational',
    constructId: 'attachment_system',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Romantik ve yakın ilişkilerde terk edilme ve sevilmeme endişesi.',
  },
  {
    facetId: 'attachment_avoidance',
    code: 'attachment_avoidance',
    nameTr: 'Bağlanma Kaçınması (ECR-R)',
    nameEn: 'Attachment Avoidance',
    domainId: 'social_relational',
    constructId: 'attachment_system',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yakın ilişkilerde duygusal yakınlıktan ve bağımlılıktan rahatsız olma.',
  },
  {
    facetId: 'cognitive_perspective_taking',
    code: 'cognitive_perspective_taking',
    nameTr: 'Bilişsel Bakış Açısı Alma (IRI-PT)',
    nameEn: 'Perspective Taking',
    domainId: 'social_relational',
    constructId: 'multidimensional_empathy',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Olaylara diğer insanların gözünden bakabilme ve zihinsel empati kurma.',
  },
  {
    facetId: 'empathic_concern',
    code: 'empathic_concern',
    nameTr: 'Duygusal Duyarlık ve İlgi (IRI-EC)',
    nameEn: 'Empathic Concern',
    domainId: 'social_relational',
    constructId: 'multidimensional_empathy',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Zor durumdaki insanlara karşı şefkat, merhamet ve yardım etme arzusu hissetme.',
  },
  {
    facetId: 'assertiveness',
    code: 'assertiveness',
    nameTr: 'Atılganlık ve Sınır Koyma',
    nameEn: 'Assertiveness',
    domainId: 'social_relational',
    constructId: 'social_agency_boundaries',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kendi haklarını ve sınırlarını başkalarını incitmeden net bir dille savunma.',
  },
  {
    facetId: 'social_connectedness',
    code: 'social_connectedness',
    nameTr: 'Sosyal Bağlılık Hissi',
    nameEn: 'Social Connectedness',
    domainId: 'social_relational',
    constructId: 'social_agency_boundaries',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Topluma, arkadaş grubuna ve çevresine ait ve entegre hissetme derecesi.',
  },
  {
    facetId: 'rejection_sensitivity_nonclinical',
    code: 'rejection_sensitivity_nonclinical',
    nameTr: 'Reddedilme Hassasiyeti',
    nameEn: 'Rejection Sensitivity',
    domainId: 'social_relational',
    constructId: 'social_agency_boundaries',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Sosyal ipuçlarında dışlanma veya reddedilme beklentisi ve buna aşırı tepki.',
  },
  {
    facetId: 'cooperation_orientation',
    code: 'cooperation_orientation',
    nameTr: 'İşbirliği Yönelimi',
    nameEn: 'Cooperation Orientation',
    domainId: 'social_relational',
    constructId: 'conflict_styles',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Çatışmalarda her iki tarafın da kazanacağı ortak çözümler üretme isteği.',
  },
  {
    facetId: 'conflict_avoidance',
    code: 'conflict_avoidance',
    nameTr: 'Çatışmadan Kaçınma',
    nameEn: 'Conflict Avoidance',
    domainId: 'social_relational',
    constructId: 'conflict_styles',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Anlaşmazlık anlarında gerginlikten kaçınmak için kendi fikrini geri çekme.',
  },

  // --- Wellbeing & Vitality (3) ---
  {
    facetId: 'flourishing_scale',
    code: 'flourishing_scale',
    nameTr: 'Psikolojik Gelişme (Diener)',
    nameEn: 'Psychological Flourishing',
    domainId: 'wellbeing_vitality',
    constructId: 'psychological_flourishing',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Yaşamda gelişme, amaç, özsaygı ve olumlu ilişkilerdeki genel başarı algısı.',
  },
  {
    facetId: 'subjective_vitality',
    code: 'subjective_vitality',
    nameTr: 'Öznel Canlılık (SVS)',
    nameEn: 'Subjective Vitality',
    domainId: 'wellbeing_vitality',
    constructId: 'psychological_flourishing',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Fiziksel ve zihinsel olarak canlı, enerjik ve dinç hissetme durumu.',
  },
  {
    facetId: 'satisfaction_with_life',
    code: 'satisfaction_with_life',
    nameTr: 'Yaşam Doyumu (SWLS)',
    nameEn: 'Satisfaction with Life',
    domainId: 'wellbeing_vitality',
    constructId: 'life_satisfaction',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Bireyin yaşamının kendi standartlarına uygunluğuna ilişkin bilişsel değerlendirmesi.',
  },

  // --- Coping & Resilience (4) ---
  {
    facetId: 'ego_resilience',
    code: 'ego_resilience',
    nameTr: 'Ego Sağlamlığı (Block ER89)',
    nameEn: 'Ego-Resilience',
    domainId: 'coping_resilience',
    constructId: 'psychological_resilience',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Stresli ve beklenmedik durumlarda psikolojik dengeyi koruyabilme kapasitesi.',
  },
  {
    facetId: 'stress_recovery',
    code: 'stress_recovery',
    nameTr: 'Stres Sonrası Hızlı Toparlanma (BRS)',
    nameEn: 'Stress Recovery',
    domainId: 'coping_resilience',
    constructId: 'psychological_resilience',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Zorlu yaşam olayları ve krizlerin ardından hızla eski gücüne kavuşabilme.',
  },
  {
    facetId: 'problem_focused_coping',
    code: 'problem_focused_coping',
    nameTr: 'Problem Odaklı Başa Çıkma',
    nameEn: 'Problem-Focused Coping',
    domainId: 'coping_resilience',
    constructId: 'coping_orientations',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Stres kaynağını ortadan kaldırmak için aktif planlama ve eyleme geçme.',
  },
  {
    facetId: 'emotion_focused_coping',
    code: 'emotion_focused_coping',
    nameTr: 'Duygu Odaklı Başa Çıkma',
    nameEn: 'Emotion-Focused Coping',
    domainId: 'coping_resilience',
    constructId: 'coping_orientations',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Stres verici durumların yarattığı içsel gerginliği ve kaygıyı yönetme.',
  },

  // --- Creativity & Curiosity (4) ---
  {
    facetId: 'joyous_exploration_curiosity',
    code: 'joyous_exploration_curiosity',
    nameTr: 'Keyifli Keşif Merakı (5DCR-JE)',
    nameEn: 'Joyous Exploration Curiosity',
    domainId: 'creativity_curiosity',
    constructId: 'epistemic_curiosity',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Dünyayı keşfetmekten ve yeni bilgiler edinmekten duyulan içsel neşe ve ilgi.',
  },
  {
    facetId: 'deprivation_sensitivity_curiosity',
    code: 'deprivation_sensitivity_curiosity',
    nameTr: 'Yoksunluk Duyarlılığı Merakı (5DCR-DS)',
    nameEn: 'Deprivation Sensitivity Curiosity',
    domainId: 'creativity_curiosity',
    constructId: 'epistemic_curiosity',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Bilgi açığını ve eksik parçaları tamamlama ihtiyacından doğan yoğun merak.',
  },
  {
    facetId: 'creative_self_efficacy',
    code: 'creative_self_efficacy',
    nameTr: 'Yaratıcı Öz-Yeterlik',
    nameEn: 'Creative Self-Efficacy',
    domainId: 'creativity_curiosity',
    constructId: 'creative_mindset',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kendi yaratıcı potansiyeline ve yenilikçi çözümler üretebileceğine duyulan inanç.',
  },
  {
    facetId: 'growth_mindset_intelligence',
    code: 'growth_mindset_intelligence',
    nameTr: 'Gelişim Zihniyeti (Dweck)',
    nameEn: 'Growth Mindset',
    domainId: 'creativity_curiosity',
    constructId: 'creative_mindset',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Zekanın ve yeteneklerin çabayla geliştirilebileceğine olan temel inanç.',
  },

  // --- Optional Dark Tetrad (4) ---
  {
    facetId: 'machiavellianism_subclinical',
    code: 'machiavellianism_subclinical',
    nameTr: 'Makyavelizm (Stratejik Manipülasyon)',
    nameEn: 'Machiavellianism',
    domainId: 'optional_dark_tetrad',
    constructId: 'dark_tetrad_traits',
    expectedItemCount: 5,
    scientificDefinitionTr: 'İlişkilerde pragmatik, stratejik ve duygudan arınmış hesapçı yaklaşım.',
  },
  {
    facetId: 'grandiose_narcissism_subclinical',
    code: 'grandiose_narcissism_subclinical',
    nameTr: 'Büyüklenmeci Narsisizm (Subklinik)',
    nameEn: 'Grandiose Narcissism',
    domainId: 'optional_dark_tetrad',
    constructId: 'dark_tetrad_traits',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Kendini üstün ve ayrıcalıklı görme; sürekli hayranlık ve ilgi bekleme.',
  },
  {
    facetId: 'psychopathy_subclinical',
    code: 'psychopathy_subclinical',
    nameTr: 'Subklinik Psikopati (Duygusal Soğukluk ve Dürtüsellik)',
    nameEn: 'Subclinical Psychopathy',
    domainId: 'optional_dark_tetrad',
    constructId: 'dark_tetrad_traits',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Düşük empati, pişmanlık eksikliği ve dürtüsel risk alma eğilimi.',
  },
  {
    facetId: 'everyday_sadism_subclinical',
    code: 'everyday_sadism_subclinical',
    nameTr: 'Gündelik Sadizm (Subklinik)',
    nameEn: 'Everyday Sadism',
    domainId: 'optional_dark_tetrad',
    constructId: 'dark_tetrad_traits',
    expectedItemCount: 5,
    scientificDefinitionTr: 'Başkalarının zor durumda kalmasından veya alay edilmesinden keyif alma.',
  },
];

// -----------------------------------------------------------------------------
// LOOKUP MAPS & INVARIANTS
// -----------------------------------------------------------------------------
export const TOTAL_MASTER_DOMAINS_COUNT = 11;
export const TOTAL_MASTER_CONSTRUCTS_COUNT = 37;
export const TOTAL_MASTER_FACETS_COUNT = 91;
export const TOTAL_ADMINISTERED_ITEMS_COUNT = 469;

export const MASTER_DOMAIN_BY_ID = new Map<string, MasterDomainDefinition>(
  MASTER_DOMAINS.map((d) => [d.domainId, d])
);

export const MASTER_CONSTRUCT_BY_ID = new Map<string, MasterConstructDefinition>(
  MASTER_CONSTRUCTS.map((c) => [c.constructId, c])
);

export const MASTER_FACET_BY_ID = new Map<string, MasterFacetDefinition>(
  MASTER_FACETS.map((f) => [f.facetId, f])
);

/**
 * Normalizes any legacy or alternative facet IDs into canonical Master Model facet ID.
 */
export function normalizeMasterFacetId(rawFacetId: string): string {
  const aliases: Record<string, string> = {
    // Legacy / alternative naming maps
    machiavellianism: 'machiavellianism_subclinical',
    grandiose_narcissism: 'grandiose_narcissism_subclinical',
    psychopathy: 'psychopathy_subclinical',
    everyday_sadism: 'everyday_sadism_subclinical',
    nfc: 'need_for_cognition',
    nfcs: 'need_for_cognitive_closure',
    erq_reappraisal: 'cognitive_reappraisal',
    erq_suppression: 'expressive_suppression',
    rses: 'core_self_esteem',
    gse: 'generalized_self_efficacy',
    swls: 'satisfaction_with_life',
  };

  return aliases[rawFacetId] || rawFacetId;
}
